import{describe,it,expect}from'vitest';import{analyzeGeometryQuestion}from'./geometryQuestionAnalyzer';import{solveGeometry}from'./geometrySolver';import{geometryDiagram}from'../visual/geometryDiagram';import{StarPolygon,Polygon,Prism,Pyramid,Antiprism,Bipyramid}from'../visual/familyGenerators';import{buildPolyhedron}from'../visual/polyhedronMesh';import{normalizeGeometryUnits}from'./geometryUnitNormalizer';import{verifyGeometry}from'./geometryVerifier';
const cases:[string,number][]=[['A circle has radius 5 cm. Find the area.',78.5398],['A rectangle has length 8 m and width 3 m. Find the area.',24],['A square has side 7 cm. Find the perimeter.',28],['A triangle has base 10 cm and height 6 cm. Find the area.',30],['A cylinder has radius 4 cm and height 10 cm. Find the volume.',502.6548],['A cone has radius 3 cm and height 12 cm. Find the volume.',113.0973],['A sphere has radius 3 cm. Find the volume.',113.0973],['A cube has side 4 cm. Find the surface area.',96],['A rectangular prism has length 4 cm width 3 cm and height 2 cm. Find the volume.',24]];
describe('geometry end-to-end',()=>{for(const[q,want]of cases)it(q,()=>{const a=analyzeGeometryQuestion(q),s=solveGeometry(a),d=geometryDiagram(a);expect(a.shape).toBeTruthy();expect(s.success).toBe(true);expect(s.value).toBeCloseTo(want,3);expect(d).toBeTruthy()})});
describe('safe failure',()=>{it('does not guess unsupported data',()=>{const a=analyzeGeometryQuestion('A triangle has one side 5 cm. Find its area.');expect(solveGeometry(a).success).toBe(false)})});
describe('geometry families',()=>{it('renders compound hexagram as two closed cycles',()=>expect(StarPolygon(6,2).primitives).toHaveLength(2));it('renders coprime pentagram as one cycle',()=>expect(StarPolygon(5,2).primitives).toHaveLength(1));it('generates reusable polygon and solid families',()=>{for(const m of[Polygon(12),Prism(7),Pyramid(8),Antiprism(5),Bipyramid(6)])expect(m.primitives.length).toBeGreaterThan(0)})});

describe('expanded formula and safety coverage',()=>{
 it('solves equilateral triangle area',()=>{const s=solveGeometry(analyzeGeometryQuestion('An equilateral triangle has side 8 cm. Find the area.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(27.7128,3)});
 it('solves cylinder lateral area',()=>{const s=solveGeometry(analyzeGeometryQuestion('A cylinder has radius 3 cm and height 7 cm. Find the lateral surface area.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(131.9469,3)});
 it('solves semicircle perimeter',()=>{const s=solveGeometry(analyzeGeometryQuestion('A semicircle has radius 5 cm. Find the perimeter.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(25.708,3)});
 it('rejects mixed units instead of silently combining them',()=>{const a=analyzeGeometryQuestion('A rectangle has length 2 m and width 30 cm. Find the area.');expect(a.warnings.some(w=>w.includes('Mixed measurement'))).toBe(true);expect(solveGeometry(a).success).toBe(false)});
});

describe('quadrilateral and prism coverage',()=>{
 it('solves rhombus area from diagonals',()=>{const a=analyzeGeometryQuestion('A rhombus has diagonals 10 cm and 6 cm. Find the area.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(30);expect(geometryDiagram(a)).toBeTruthy()});
 it('solves kite area from diagonals',()=>{const a=analyzeGeometryQuestion('A kite has diagonals 12 m and 7 m. Find the area.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(42);expect(geometryDiagram(a)).toBeTruthy()});
 it('solves triangular prism volume',()=>{const a=analyzeGeometryQuestion('A triangular prism has base 8 cm, height 5 cm, and length 12 cm. Find the volume.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(240);expect(geometryDiagram(a)).toBeTruthy()});
});
describe('polyhedron visibility',()=>{
 it('classifies visible and hidden cube edges',()=>{const m=buildPolyhedron('cube');expect(m).toBeTruthy();const semantics=m!.primitives.map(p=>p.semantic);expect(semantics).toContain('polyhedron-edge');expect(semantics).toContain('hidden-edge')});
 it('renders the icosahedron mesh',()=>{const m=buildPolyhedron('icosahedron');expect(m).toBeTruthy();expect(m!.primitives.length).toBe(30)});
});
describe('unit normalization',()=>{
 it('converts mixed compatible length units before solving',()=>{const raw=analyzeGeometryQuestion('A rectangle has length 2 m and width 30 cm. Find the area.');const n=normalizeGeometryUnits(raw);expect(n.converted).toBe(true);expect(n.analysis.givens.w).toBeCloseTo(.3,6);const s=solveGeometry(n.analysis);expect(s.success).toBe(true);expect(s.value).toBeCloseTo(.6,6);expect(s.unit).toBe('m²')});
 it('converts imperial lengths consistently',()=>{const raw=analyzeGeometryQuestion('A rectangle has length 2 ft and width 12 in. Find the area.');const n=normalizeGeometryUnits(raw);expect(n.analysis.givens.w).toBeCloseTo(1,6);expect(solveGeometry(n.analysis).value).toBeCloseTo(2,6)});
});
describe('geometry verification',()=>{it('checks output dimensions and equation substitution',()=>{const a=analyzeGeometryQuestion('A right triangle has legs 3 cm and 4 cm. Find the hypotenuse.');const s=solveGeometry(a),v=verifyGeometry(a,s);expect(s.value).toBe(5);expect(v.valid).toBe(true);expect(v.checks).toContain('Answer passes equation substitution.')});});