import type{GeometryQuestionAnalysis}from'./geometryQuestionAnalyzer';import{polygonSideCount}from'./geometryQuestionAnalyzer';
export interface GeometrySolveResult{success:boolean;formula:string|null;value:number|null;unit:string|null;steps:string[];message:string;exact?:string}
const round=(x:number)=>Number(x.toFixed(4));const base=(a:GeometryQuestionAnalysis)=>Object.values(a.units).find(Boolean)??'';const unit=(a:GeometryQuestionAnalysis,p=1)=>{const u=base(a);return u?u+(p===2?'²':p===3?'³':''):null};
export function solveGeometry(a:GeometryQuestionAnalysis):GeometrySolveResult{
 if(a.warnings.some(w=>w.startsWith('Mixed measurement')))return{success:false,formula:null,value:null,unit:null,steps:[],message:'Convert all measurements to the same unit before solving.'};
 const g=a.givens,s=a.shape,t=a.target;let f:string|null=null,v:number|null=null,p=1,exact:string|undefined;const n=polygonSideCount(s,g);
 if(a.regularPolygon&&n!=null&&n>=3&&t==='perimeter'&&g.s!=null){f='P = ns';v=n*g.s}else if(a.regularPolygon&&n!=null&&n>=3&&t==='area'&&g.ap!=null&&g.s!=null){f='A = ½aP, P = ns';v=.5*g.ap*n*g.s;p=2}else if(n!=null&&n>=3&&t==='interior-angle-sum'){f='S = (n−2)180°';v=(n-2)*180}else if(a.regularPolygon&&n!=null&&n>=3&&t==='interior-angle'){f='θ = (n−2)180°/n';v=(n-2)*180/n}else if(a.regularPolygon&&n!=null&&n>=3&&t==='exterior-angle'){f='θ = 360°/n';v=360/n}else if(s==='circle'&&t==='area'&&(g.r!=null||g.d!=null)){const r=g.r??g.d/2;f='A = πr²';v=Math.PI*r*r;p=2;exact=`${round(r*r)}π`}else if(s==='circle'&&t==='circumference'&&(g.r!=null||g.d!=null)){const r=g.r??g.d/2;f='C = 2πr';v=2*Math.PI*r;exact=`${round(2*r)}π`}else if(s==='circle'&&t==='diameter'&&g.r!=null){f='d = 2r';v=2*g.r}else if(s==='circle'&&t==='radius'&&g.d!=null){f='r = d/2';v=g.d/2}
 else if(s==='semicircle'&&t==='area'&&(g.r!=null||g.d!=null)){const r=g.r??g.d/2;f='A = ½πr²';v=.5*Math.PI*r*r;p=2}else if(s==='semicircle'&&t==='perimeter'&&(g.r!=null||g.d!=null)){const r=g.r??g.d/2;f='P = πr + 2r';v=Math.PI*r+2*r}
 else if(s==='rectangle'&&t==='area'&&g.l!=null&&g.w!=null){f='A = lw';v=g.l*g.w;p=2}else if(s==='rectangle'&&t==='perimeter'&&g.l!=null&&g.w!=null){f='P = 2(l+w)';v=2*(g.l+g.w)}
 else if(s==='square'&&t==='area'&&g.s!=null){f='A = s²';v=g.s**2;p=2}else if(s==='square'&&t==='perimeter'&&g.s!=null){f='P = 4s';v=4*g.s}
 else if(s==='parallelogram'&&t==='area'&&g.b!=null&&g.h!=null){f='A = bh';v=g.b*g.h;p=2}
 else if((s==='rhombus'||s==='kite')&&t==='area'&&g.d1!=null&&g.d2!=null){f='A = ½d₁d₂';v=.5*g.d1*g.d2;p=2}else if(s==='rhombus'&&t==='perimeter'&&g.s!=null){f='P = 4s';v=4*g.s}
 else if(s==='trapezoid'&&t==='area'&&g.a!=null&&g.b!=null&&g.h!=null){f='A = ½(a+b)h';v=.5*(g.a+g.b)*g.h;p=2}
 else if(s?.includes('triangle')&&t==='area'&&g.b!=null&&g.h!=null){f='A = ½bh';v=.5*g.b*g.h;p=2}else if(s==='equilateral triangle'&&t==='area'&&g.s!=null){f='A = (√3/4)s²';v=Math.sqrt(3)*g.s**2/4;p=2}else if(s==='equilateral triangle'&&t==='perimeter'&&g.s!=null){f='P = 3s';v=3*g.s}else if(s==='right triangle'&&t==='hypotenuse'&&g.a!=null&&g.b!=null){f='c = √(a²+b²)';v=Math.hypot(g.a,g.b)}else if(s==='right triangle'&&t==='leg'&&g.c!=null&&(g.a!=null||g.b!=null)){const leg=g.a??g.b;f='a = √(c²−b²)';v=g.c>leg?Math.sqrt(g.c**2-leg**2):null}else if(s?.includes('triangle')&&t==='perimeter'&&g.a!=null&&g.b!=null&&g.c!=null){f='P = a+b+c';v=g.a+g.b+g.c}
 else if(s==='cube'&&t==='volume'&&g.s!=null){f='V = s³';v=g.s**3;p=3}else if(s==='cube'&&t==='surface-area'&&g.s!=null){f='SA = 6s²';v=6*g.s**2;p=2}
 else if(s==='rectangular prism'&&t==='volume'&&g.l!=null&&g.w!=null&&g.h!=null){f='V = lwh';v=g.l*g.w*g.h;p=3}else if(s==='rectangular prism'&&t==='surface-area'&&g.l!=null&&g.w!=null&&g.h!=null){f='SA = 2(lw+lh+wh)';v=2*(g.l*g.w+g.l*g.h+g.w*g.h);p=2}
 else if(s==='triangular prism'&&t==='volume'&&g.b!=null&&g.h!=null&&g.l!=null){f='V = (½bh)L';v=.5*g.b*g.h*g.l;p=3}else if(s==='triangular prism'&&t==='surface-area'&&g.b!=null&&g.h!=null&&g.l!=null&&g.P!=null){f='SA = 2B+PL, B = ½bh';v=g.b*g.h+g.P*g.l;p=2}else if(s==='pyramid'&&t==='volume'&&g.B!=null&&g.h!=null){f='V = ⅓Bh';v=g.B*g.h/3;p=3}
 else if(s==='cylinder'&&t==='volume'&&(g.r!=null||g.d!=null)&&g.h!=null){{const r=g.r??g.d/2;f='V = πr²h';v=Math.PI*r**2*g.h};p=3}else if(s==='cylinder'&&t==='surface-area'&&g.r!=null&&g.h!=null){f='SA = 2πr(r+h)';v=2*Math.PI*g.r*(g.r+g.h);p=2}else if(s==='cylinder'&&t==='lateral-area'&&g.r!=null&&g.h!=null){f='LA = 2πrh';v=2*Math.PI*g.r*g.h;p=2}
 else if(s==='cone'&&t==='volume'&&g.r!=null&&g.h!=null){f='V = ⅓πr²h';v=Math.PI*g.r**2*g.h/3;p=3}else if(s==='cone'&&t==='surface-area'&&g.r!=null&&(g.sl!=null||g.h!=null)){const sl=g.sl??Math.hypot(g.r,g.h);f='SA = πr(r+ℓ)';v=Math.PI*g.r*(g.r+sl);p=2}else if(s==='cone'&&t==='lateral-area'&&g.r!=null&&(g.sl!=null||g.h!=null)){const sl=g.sl??Math.hypot(g.r,g.h);f='LA = πrℓ';v=Math.PI*g.r*sl;p=2}
 else if(s==='sphere'&&t==='volume'&&g.r!=null){f='V = 4πr³/3';v=4*Math.PI*g.r**3/3;p=3}else if(s==='sphere'&&t==='surface-area'&&g.r!=null){f='SA = 4πr²';v=4*Math.PI*g.r**2;p=2}
 if(v==null||!Number.isFinite(v))return{success:false,formula:null,value:null,unit:null,steps:[],message:'I need more information or this formula path is not implemented yet.'};const value=round(v),uu=t?.includes('angle')?'°':unit(a,p);return{success:true,formula:f,value,unit:uu,exact,steps:[`Find: ${t}.`,`Formula: ${f}.`,'Substitute the given measurements.',`Answer: ${exact?exact+' ≈ ':''}${value}${uu?' '+uu:''}.`],message:'Solved deterministically.'};
}