export interface GeometryQuestionAnalysis{originalQuestion:string;shape:string|null;givens:Record<string,number>;units:Record<string,string>;target:string|null;regularPolygon:boolean;confidence:number;warnings:string[]}
const num=(s:string)=>Number(s.replace(/,/g,''));const U='(?:mm|cm|km|m|in|ft|yd)(?:\\^?[23]|[²³])?';const canonicalUnit=(u:string)=>u.replace('^2','²').replace('^3','³').replace(/(mm|cm|km|m|in|ft|yd)([23])$/,'$1$2').replace(/2$/,'²').replace(/3$/,'³');const polygonNames:Record<string,number>={pentagon:5,hexagon:6,heptagon:7,octagon:8,nonagon:9,decagon:10,undecagon:11,dodecagon:12,tridecagon:13,tetradecagon:14,pentadecagon:15,hexadecagon:16,heptadecagon:17,octadecagon:18,enneadecagon:19,icosagon:20};
const capture=(q:string,names:string[])=>{for(const name of names){const rx=new RegExp('(?:'+name+')\\s*(?:=|is|of|measures?|has)?\\s*(?:a\\s+)?([\\d,.]+)\\s*('+U+')?(?=\\s|[?.,;]|$)','i'),m=q.match(rx);if(m)return{value:num(m[1]),unit:m[2]?canonicalUnit(m[2]):''}}return null};
export function normalizeGeometryQuestion(q:string){return q.replace(/\\\[|\\\]|\\\(|\\\)/g,'').replace(/\\text\s*\{([^{}]*)\}/g,'$1').replace(/\\frac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g,'$1/$2').replace(/\\(?:approx|simeq)/g,'≈').replace(/\\pi\b/g,'π').replace(/\\circ|\^\{?\\circ\}?/g,'°').replace(/\{([^{}]+)\}/g,'$1').replace(/\\,/g,' ').replace(/\\([A-Za-z]+)/g,'$1').replace(/\s+/g,' ').trim()}
function requestedTarget(q:string){const t=q.toLowerCase(),m=[...t.matchAll(/(?:what\s+is|what's|find|calculate|determine|compute|solve\s+for)\s+(?:the\s+)?([^?.;]+)/gi)],r=(m.at(-1)?.[1]??t).trim();
 if(/sector\s+area|area\s+of\s+(?:the\s+)?sector/.test(r))return'sector-area';
 if(/lateral\s+(?:surface\s+)?area/.test(r))return'lateral-area';
 if(/surface\s+area/.test(r))return'surface-area';
 if(/arc\s+length|length\s+of\s+(?:an?\s+|the\s+)?arc/.test(r))return'arc-length';
 if(/interior\s+angle\s+sum|sum\s+of.*interior\s+angles/.test(r))return'interior-angle-sum';
 if(/each\s+interior\s+angle|interior\s+angle/.test(r))return'interior-angle';
 if(/each\s+exterior\s+angle|exterior\s+angle/.test(r))return'exterior-angle';
 if(/missing\s+angle|unknown\s+angle|third\s+angle/.test(r))return'missing-angle';
 if(/number\s+of\s+diagonals|how\s+many\s+diagonals/.test(r))return'diagonals';
 if(/midsegment|midline/.test(r))return'midsegment';
 if(/chord/.test(r))return'chord';
 if(/shortest\s+side|short\s+leg/.test(r))return'shortest-side';
 if(/missing\s+leg|other\s+leg|unknown\s+leg/.test(r))return'leg';
 if(/hypotenuse/.test(r))return'hypotenuse';
 if(/circumference/.test(r))return'circumference';
 if(/perimeter/.test(r)&&!/base\s+perimeter|perimeter\s+of\s+the\s+base/.test(r))return'perimeter';
 if(/volume/.test(r))return'volume';
 if(/base\s+area|area\s+of\s+the\s+base/.test(r))return'base';
 if(/area/.test(r))return'area';
 if(/slant\s+height/.test(r))return'slant-height';
 if(/diameter/.test(r))return'diameter';
 if(/radius/.test(r))return'radius';
 if(/diagonal/.test(r))return'diagonal';
 if(/length/.test(r))return'length';
 if(/width/.test(r))return'width';
 if(/height|altitude/.test(r))return'height';
 if(/base/.test(r))return'base';
 if(/side\s+length|\bside\b/.test(r))return'side';
 return null}
export function analyzeGeometryQuestion(q:string):GeometryQuestionAnalysis{q=normalizeGeometryQuestion(q);const t=q.toLowerCase(),g:Record<string,number>={},units:Record<string,string>={},warnings:string[]=[];const fields:[string,string[]][]=[['SA',['total surface area','surface area']],['LA',['lateral surface area','lateral area']],['B',['base area','area of the base']],['V',['volume']],['C',['circumference']],['P',['base perimeter','perimeter of the base','perimeter']],['A',['area']],['r',['radius']],['d',['diameter']],['l',['length']],['w',['width']],['h',['height','altitude']],['b',['base']],['s',['side length','side']],['a',['side a','leg a']],['c',['hypotenuse','side c','leg c']],['sl',['slant height']],['d1',['diagonal 1','first diagonal']],['d2',['diagonal 2','second diagonal']],['ap',['apothem']],['m',['midsegment','midline']],['theta',['central angle']]];
 for(const[sym,names]of fields){const x=capture(q,names);if(x){g[sym]=x.value;if(x.unit)units[sym]=x.unit}}
 // Natural-language measurements: allow "height of 5" and "diameter of 16" with no unit.
 const angleValues=[...q.matchAll(/(\d+(?:\.\d+)?)\s*(?:°|degrees?)/gi)].map(m=>Number(m[1]));if(angleValues.length){g.angle1=angleValues[0];units.angle1='°';if(angleValues.length>1){g.angle2=angleValues[1];units.angle2='°'}}
 if(g.theta==null){const ca=q.match(/central angle(?:\s+(?:of|is|=))?\s*(\d+(?:\.\d+)?)\s*(?:°|degrees?)/i);if(ca)g.theta=Number(ca[1])}if(g.theta!=null){delete g.angle1;if(angleValues.length>1){g.angle1=angleValues.find(v=>v!==g.theta)??angleValues[0]}}
 const rectilinearMatch=q.match(/(?:outside\s+)?side lengths?\s*(?:(?:of|are)\s*)?(?:=\s*)?([^.?]+)/i);const rectilinearText=(rectilinearMatch?.[1]??'').replace(/\bunits?\b.*$/i,'');const rectilinear=[...rectilinearText.matchAll(/\d+(?:\.\d+)?/g)].map(m=>Number(m[0]));const legPair=/\\blegs?(?:\\s+of\\s+length)?\\s*(?:are\\s*|=\\s*)?(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?\\s*(?:and|,)\\s*(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?/i.exec(q);if(legPair){g.a=num(legPair[1]);g.b=num(legPair[3]);if(legPair[2])units.a=legPair[2];if(legPair[4])units.b=legPair[4]}const sidePair=/\\bsides?\\s*(?:are\\s*|=\\s*)?(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?\\s*(?:and|,)\\s*(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?/i.exec(q);if(sidePair&&g.a==null){g.a=num(sidePair[1]);g.b=num(sidePair[3]);if(sidePair[2])units.a=sidePair[2];if(sidePair[4])units.b=sidePair[4]}const basePair=/\\bbases?(?:\\s+of\\s+length)?\\s*(?:are\\s*|of\\s*|=\\s*)?(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?\\s*(?:and|,)\\s*(\\d+(?:\\.\\d+)?)\\s*(mm|cm|km|m|in|ft|yd)?/i.exec(q);if(basePair){g.a=num(basePair[1]);g.b=num(basePair[3]);if(basePair[2])units.a=basePair[2];if(basePair[4])units.b=basePair[4]}const three=new RegExp('(?:side lengths?|three sides?)\\s*(?:are|=)?\\s*([\\d.]+)\\s*('+U+')?\\s*,?\\s*([\\d.]+)\\s*('+U+')?\\s*(?:,?\\s*and\\s*|,\\s*)([\\d.]+)\\s*('+U+')?','i').exec(q);if(three){g.a=num(three[1]);g.b=num(three[3]);g.c=num(three[5]);if(three[2])units.a=three[2];if(three[4])units.b=three[4];if(three[6])units.c=three[6]}const diag=new RegExp('diagonals?(?:\\s+of\\s+(?:a|the)\\s+[a-z -]+)?(?:\\s+(?:have|has))?(?:\\s+lengths?)?\\s*(?:(?:are|of)|=)?\\s*([\\d.]+)\\s*('+U+')?\\s*(?:and|,)\\s*([\\d.]+)\\s*('+U+')?','i').exec(q);if(diag){g.d1=num(diag[1]);g.d2=num(diag[3]);if(diag[2])units.d1=diag[2];if(diag[4])units.d2=diag[4]}
 let shape:string|null=null;if(/\b(?:box|rectangular box|cuboid)\b/.test(t)){shape='rectangular prism';}else if(/rectilinear|composite\s+(?:rectilinear\s+)?(?:figure|polygon|shape)/.test(t)){shape='rectilinear figure';if(rectilinear.length>=3)rectilinear.forEach((v,i)=>g['side'+(i+1)]=v)}for(const s of ['rectangular prism','triangular prism','hemisphere','tetrahedron','octahedron','pyramid','right-angled triangle','right angle triangle','right triangle','equilateral triangle','isosceles triangle','regular polygon','parallelogram','trapezoid','rhombus','kite','rectangle','square','triangle','semicircle','circle','cylinder','cone','sphere','cube'])if(!shape&&t.includes(s)){shape=s;break}if(!shape)for(const name of Object.keys(polygonNames))if(t.includes(name)){shape=name;g.n=polygonNames[name];break}const nMatch=t.match(/regular\s+(\d+)\s*[- ]?gon/);if(nMatch){shape='regular polygon';g.n=Number(nMatch[1])}const regularPolygon=!!(nMatch||/\bregular polygon\b/.test(t)||Object.keys(polygonNames).some(name=>new RegExp('\\bregular\\s+'+name+'\\b').test(t)));
 let target:string|null=requestedTarget(q);if(shape==='circle'&&(target==='arc-length'||target==='sector-area'||target==='chord')&&g.theta==null&&g.angle1!=null){g.theta=g.angle1;units.theta='°';delete g.angle1;delete units.angle1}const piMatch=q.match(/(?:π|pi)\s*(?:≈|~=|=|about|approximately)?\s*(3(?:\.\d+)?)/i);if(piMatch)g.__pi=Number(piMatch[1]);
 if(g.SA!=null||g.LA!=null||g.B!=null){if(!/\barea\b\s*(?:=|is|of|measures?|has)\s*[\d,.]+/i.test(q))delete g.A;}const ask=requestedTarget(q);if(ask==='area')delete g.A;if(ask==='perimeter')delete g.P;if(ask==='volume')delete g.V;if(ask==='circumference')delete g.C;if(ask==='surface-area')delete g.SA;if(ask==='lateral-area')delete g.LA;if(shape==='right-angled triangle'||shape==='right angle triangle')shape='right triangle';if(!shape)warnings.push('Geometry shape was not recognized.');if(!target)warnings.push('Requested measurement was not recognized.');const seenUnits=[...new Set(Object.values(units).filter(v=>v&&v!=='°').map(v=>v.replace(/(?:\^?[23]|[²³])$/,'')))];if(seenUnits.length>1)warnings.push('Mixed measurement units must be converted before solving.');return{originalQuestion:q,shape,givens:g,units,target,regularPolygon,confidence:(shape?0.45:0)+(target?0.3:0)+(Object.keys(g).length?0.25:0),warnings}}
export const polygonSideCount=(shape:string|null,g:Record<string,number>)=>g.n??(shape?polygonNames[shape]:undefined);