export interface GeometryQuestionAnalysis{originalQuestion:string;shape:string|null;givens:Record<string,number>;units:Record<string,string>;target:string|null;regularPolygon:boolean;confidence:number;warnings:string[]}
const num=(s:string)=>Number(s.replace(/,/g,''));const U='(?:mm|cm|km|m|in|ft|yd)';const polygonNames:Record<string,number>={pentagon:5,hexagon:6,heptagon:7,octagon:8,nonagon:9,decagon:10,undecagon:11,dodecagon:12,tridecagon:13,tetradecagon:14,pentadecagon:15,hexadecagon:16,heptadecagon:17,octadecagon:18,enneadecagon:19,icosagon:20};
const capture=(q:string,names:string[])=>{for(const name of names){const rx=new RegExp('(?:'+name+')\\s*(?:=|is|of|measures?|has)?\\s*(?:a\\s+)?([\\d,.]+)\\s*('+U+')?(?=\\s|[?.,;]|$)','i'),m=q.match(rx);if(m)return{value:num(m[1]),unit:m[2]??''}}return null};
export function normalizeGeometryQuestion(q:string){return q.replace(/\\\[|\\\]|\\\(|\\\)/g,'').replace(/\\circ|\^\{?\\circ\}?/g,'°').replace(/\{([^{}]+)\}/g,'$1').replace(/\\,/g,' ').replace(/\s+/g,' ').trim()}
export function analyzeGeometryQuestion(q:string):GeometryQuestionAnalysis{q=normalizeGeometryQuestion(q);const t=q.toLowerCase(),g:Record<string,number>={},units:Record<string,string>={},warnings:string[]=[];const fields:[string,string[]][]=[['r',['radius']],['d',['diameter']],['l',['length']],['w',['width']],['h',['height','altitude']],['b',['base']],['s',['side length','side']],['a',['side a','leg a']],['c',['hypotenuse','side c','leg c']],['sl',['slant height']],['d1',['diagonal 1','first diagonal']],['d2',['diagonal 2','second diagonal']],['ap',['apothem']],['P',['base perimeter','perimeter of the base']],['B',['base area','area of the base']],['theta',['central angle']]];
 for(const[sym,names]of fields){const x=capture(q,names);if(x){g[sym]=x.value;if(x.unit)units[sym]=x.unit}}
 // Natural-language measurements: allow "height of 5" and "diameter of 16" with no unit.
 const angleValues=[...q.matchAll(/(\d+(?:\.\d+)?)\s*(?:°|degrees?)/gi)].map(m=>Number(m[1]));if(angleValues.length){g.angle1=angleValues[0];if(angleValues.length>1)g.angle2=angleValues[1]}
 if(g.theta==null){const ca=q.match(/central angle(?:\s+(?:of|is|=))?\s*(\d+(?:\.\d+)?)\s*(?:°|degrees?)/i);if(ca)g.theta=Number(ca[1])}if(g.theta!=null){delete g.angle1;if(angleValues.length>1){g.angle1=angleValues.find(v=>v!==g.theta)??angleValues[0]}}
 const rectilinearMatch=q.match(/(?:outside\s+)?side lengths?\s*(?:(?:of|are)\s*)?(?:=\s*)?([^.?]+)/i);const rectilinearText=(rectilinearMatch?.[1]??'').replace(/\bunits?\b.*$/i,'');const rectilinear=[...rectilinearText.matchAll(/\d+(?:\.\d+)?/g)].map(m=>Number(m[0]));const pair=new RegExp('(?:legs?|sides?)\\s*(?:are|=)?\\s*([\\d.]+)\\s*('+U+')?\\s*(?:and|,)\\s*([\\d.]+)\\s*('+U+')?','i').exec(q);if(pair){g.a=num(pair[1]);g.b=num(pair[3]);if(pair[2])units.a=pair[2];if(pair[4])units.b=pair[4]}const three=new RegExp('(?:side lengths?|three sides?)\\s*(?:are|=)?\\s*([\\d.]+)\\s*('+U+')?\\s*,?\\s*([\\d.]+)\\s*('+U+')?\\s*(?:,?\\s*and\\s*|,\\s*)([\\d.]+)\\s*('+U+')?','i').exec(q);if(three){g.a=num(three[1]);g.b=num(three[3]);g.c=num(three[5]);if(three[2])units.a=three[2];if(three[4])units.b=three[4];if(three[6])units.c=three[6]}const diag=new RegExp('diagonals?\\s*(?:are|=)?\\s*([\\d.]+)\\s*('+U+')?\\s*(?:and|,)\\s*([\\d.]+)\\s*('+U+')?','i').exec(q);if(diag){g.d1=num(diag[1]);g.d2=num(diag[3]);if(diag[2])units.d1=diag[2];if(diag[4])units.d2=diag[4]}
 let shape:string|null=null;if(/rectilinear|composite\s+(?:rectilinear\s+)?(?:figure|polygon|shape)/.test(t)){shape='rectilinear figure';if(rectilinear.length>=3)rectilinear.forEach((v,i)=>g['side'+(i+1)]=v)}for(const s of ['rectangular prism','triangular prism','pyramid','right triangle','equilateral triangle','isosceles triangle','regular polygon','parallelogram','trapezoid','rhombus','kite','rectangle','square','triangle','semicircle','circle','cylinder','cone','sphere','cube'])if(!shape&&t.includes(s)){shape=s;break}if(!shape)for(const name of Object.keys(polygonNames))if(t.includes(name)){shape=name;g.n=polygonNames[name];break}const nMatch=t.match(/regular\s+(\d+)\s*[- ]?gon/);if(nMatch){shape='regular polygon';g.n=Number(nMatch[1])}const regularPolygon=!!(nMatch||/\bregular polygon\b/.test(t)||Object.keys(polygonNames).some(name=>new RegExp('\\bregular\\s+'+name+'\\b').test(t)));
 let target:string|null=null;if(/(?:what\s+is|find|calculate|determine)(?:\s+the)?\s+area\b|\barea\s+of\b/.test(t))target='area';else if(/missing angle|unknown angle|third angle/.test(t))target='missing-angle';else if(/shortest side|short leg/.test(t))target='shortest-side';else if(/arc length|length of (?:an|the) arc/.test(t))target='arc-length';else if(/arc length/.test(t))target='arc-length';else if(/sector area|area of (?:the )?sector/.test(t))target='sector-area';else if(/interior angle sum|sum of (?:the )?(?:measures? of (?:the )?)?interior angles/.test(t))target='interior-angle-sum';else if(/each interior angle|interior angle/.test(t))target='interior-angle';else if(/each exterior angle|exterior angle/.test(t))target='exterior-angle';else if(/lateral (?:surface )?area/.test(t))target='lateral-area';else if(/surface area/.test(t))target='surface-area';else if(/circumference/.test(t))target='circumference';else if(/perimeter/.test(t)&&!/perimeter of the base|base perimeter/.test(t))target='perimeter';else if(/volume/.test(t))target='volume';else if(/missing leg|other leg|unknown leg/.test(t))target='leg';else if(/(?:find|calculate|what is|determine)(?: the)? hypotenuse/.test(t))target='hypotenuse';else if(/\barea\b/.test(t))target='area';else if(/diameter/.test(t)&&g.d===undefined)target='diameter';else if(/radius/.test(t)&&g.r===undefined)target='radius';else if(/diagonal/.test(t)&&g.d1===undefined&&g.d2===undefined)target='diagonal';
 const requestedArea=/\barea\b/.test(t)&&!/base area|area of the base/.test(t);const requestedPerimeter=/\bperimeter\b/.test(t)&&!/base perimeter|perimeter of the base/.test(t);if(requestedArea)delete g.A;if(requestedPerimeter)delete g.Pall;if(!shape)warnings.push('Geometry shape was not recognized.');if(!target)warnings.push('Requested measurement was not recognized.');const seenUnits=[...new Set(Object.values(units).filter(Boolean))];if(seenUnits.length>1)warnings.push('Mixed measurement units must be converted before solving.');return{originalQuestion:q,shape,givens:g,units,target,regularPolygon,confidence:(shape?0.45:0)+(target?0.3:0)+(Object.keys(g).length?0.25:0),warnings}}
export const polygonSideCount=(shape:string|null,g:Record<string,number>)=>g.n??(shape?polygonNames[shape]:undefined);