import{describe,it,expect}from'vitest';import{analyzeGeometryQuestion}from'./geometryQuestionAnalyzer';import{solveGeometry}from'./geometrySolver';import{geometryDiagram}from'../visual/geometryDiagram';import{StarPolygon,Polygon,Prism,Pyramid,Antiprism,Bipyramid}from'../visual/familyGenerators';import{buildPolyhedron}from'../visual/polyhedronMesh';import{normalizeGeometryUnits}from'./geometryUnitNormalizer';import{verifyGeometry}from'./geometryVerifier';import{coordinateAxes,transformPoint,distance,midpoint,slope}from'../visual/coordinateGeometry';import{buildGeometry}from'../visual/geometryEngine';import{triangleConstructions}from'../visual/geometryConstructions';import{hypercube,simplex,crossPolytope,tesseract}from'../visual/higherDimensionalGeometry';import{buildParametricCurve}from'../visual/curveGenerators';import{buildQuadric,buildTorus}from'../visual/surfaceGenerators';import{sierpinskiTriangle,kochSnowflake,cantorSet,regularTiling}from'../visual/fractalTilingGenerators';import{buildSpaceCurve}from'../visual/spaceCurveGenerators';import{buildSpecialCurve}from'../visual/specialCurveGenerators';import{buildTopologySurface}from'../visual/topologySurfaceGenerators';import{solidNet,crossSection}from'../visual/spatialGeometry';
const cases:[string,number][]=[['A circle has radius 5 cm. Find the area.',78.5398],['A rectangle has length 8 m and width 3 m. Find the area.',24],['A square has side 7 cm. Find the perimeter.',28],['A triangle has base 10 cm and height 6 cm. Find the area.',30],['A cylinder has radius 4 cm and height 10 cm. Find the volume.',502.6548],['A cone has radius 3 cm and height 12 cm. Find the volume.',113.0973],['A sphere has radius 3 cm. Find the volume.',113.0973],['A cube has side 4 cm. Find the surface area.',96],['A rectangular prism has length 4 cm width 3 cm and height 2 cm. Find the volume.',24]];
describe('geometry end-to-end',()=>{for(const[q,want]of cases)it(q,()=>{const a=analyzeGeometryQuestion(q),s=solveGeometry(a),d=geometryDiagram(a);expect(a.shape).toBeTruthy();expect(s.success).toBe(true);expect(s.value).toBeCloseTo(want,3);expect(d).toBeTruthy()})});
describe('safe failure',()=>{it('does not guess unsupported data',()=>{const a=analyzeGeometryQuestion('A triangle has one side 5 cm. Find its area.');expect(solveGeometry(a).success).toBe(false)})});
describe('geometry families',()=>{it('renders compound hexagram as two closed cycles',()=>expect(StarPolygon(6,2).primitives).toHaveLength(2));it('renders coprime pentagram as one cycle',()=>expect(StarPolygon(5,2).primitives).toHaveLength(1));it('generates reusable polygon and solid families',()=>{for(const m of[Polygon(12),Prism(7),Pyramid(8),Antiprism(5),Bipyramid(6)])expect(m.primitives.length).toBeGreaterThan(0)})});

describe('expanded formula and safety coverage',()=>{
 it('solves equilateral triangle area',()=>{const s=solveGeometry(analyzeGeometryQuestion('An equilateral triangle has side 8 cm. Find the area.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(27.7128,3)});
 it('solves cylinder lateral area',()=>{const s=solveGeometry(analyzeGeometryQuestion('A cylinder has radius 3 cm and height 7 cm. Find the lateral surface area.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(131.9469,3)});
 it('solves semicircle perimeter',()=>{const s=solveGeometry(analyzeGeometryQuestion('A semicircle has radius 5 cm. Find the perimeter.'));expect(s.success).toBe(true);expect(s.value).toBeCloseTo(25.708,3)});
 it('rejects mixed units instead of silently combining them',()=>{const a=analyzeGeometryQuestion('A rectangle has length 2 m and width 30 cm. Find the area.');expect(a.warnings.some(w=>w.includes('Mixed measurement'))).toBe(true);expect(solveGeometry(a).success).toBe(false)});
});

describe('quadrilateral and prism coverage',()=>{
 it('solves rhombus area from diagonals',()=>{const a=analyzeGeometryQuestion('A rhombus has diagonals 10 cm and 6 cm. Find the area.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(30);expect(geometryDiagram(a)).toBeTruthy()});
 it('solves kite area from diagonals',()=>{const a=analyzeGeometryQuestion('A kite has diagonals 12 m and 7 m. Find the area.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(42);expect(geometryDiagram(a)).toBeTruthy()});
 it('solves triangular prism volume',()=>{const a=analyzeGeometryQuestion('A triangular prism has base 8 cm, height 5 cm, and length 12 cm. Find the volume.');const s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBe(240);expect(geometryDiagram(a)).toBeTruthy()});
});
describe('polyhedron visibility',()=>{
 it('classifies visible and hidden cube edges',()=>{const m=buildPolyhedron('cube');expect(m).toBeTruthy();const semantics=m!.primitives.map(p=>p.semantic);expect(semantics).toContain('polyhedron-edge');expect(semantics).toContain('hidden-edge')});
 it('renders the icosahedron mesh',()=>{const m=buildPolyhedron('icosahedron');expect(m).toBeTruthy();expect(m!.primitives.length).toBe(30)});
});
describe('unit normalization',()=>{
 it('converts mixed compatible length units before solving',()=>{const raw=analyzeGeometryQuestion('A rectangle has length 2 m and width 30 cm. Find the area.');const n=normalizeGeometryUnits(raw);expect(n.converted).toBe(true);expect(n.analysis.givens.w).toBeCloseTo(.3,6);const s=solveGeometry(n.analysis);expect(s.success).toBe(true);expect(s.value).toBeCloseTo(.6,6);expect(s.unit).toBe('m²')});
 it('converts imperial lengths consistently',()=>{const raw=analyzeGeometryQuestion('A rectangle has length 2 ft and width 12 in. Find the area.');const n=normalizeGeometryUnits(raw);expect(n.analysis.givens.w).toBeCloseTo(1,6);expect(solveGeometry(n.analysis).value).toBeCloseTo(2,6)});
});
describe('geometry verification',()=>{it('checks output dimensions and equation substitution',()=>{const a=analyzeGeometryQuestion('A right triangle has legs 3 cm and 4 cm. Find the hypotenuse.');const s=solveGeometry(a),v=verifyGeometry(a,s);expect(s.value).toBe(5);expect(v.valid).toBe(true);expect(v.checks).toContain('Answer passes independent equation substitution.')});});
describe('diagram semantics',()=>{it('labels diagonal measurements on rhombus',()=>{const a=analyzeGeometryQuestion('A rhombus has diagonals 10 cm and 6 cm. Find the area.');const d=geometryDiagram(a)!;const labels=d.primitives.filter(p=>p.type==='text').map(p=>String(p.attrs.text));expect(labels.some(x=>x.includes('d₁ = 10 cm'))).toBe(true);expect(labels.some(x=>x.includes('d₂ = 6 cm'))).toBe(true)});});
describe('independent verification coverage',()=>{it('verifies cylinder volume independently',()=>{const a=analyzeGeometryQuestion('A cylinder has radius 4 cm and height 10 cm. Find its volume.');const s=solveGeometry(a);expect(verifyGeometry(a,s).valid).toBe(true)});it('verifies rectangular prism volume independently',()=>{const a=analyzeGeometryQuestion('A rectangular prism has length 4 cm width 3 cm and height 2 cm. Find the volume.');expect(verifyGeometry(a,solveGeometry(a)).valid).toBe(true)});});
describe('regular polygon family solve and draw',()=>{
 it('solves a decagon perimeter',()=>{const a=analyzeGeometryQuestion('A regular decagon has side 6 cm. Find the perimeter.');const s=solveGeometry(a);expect(a.givens.n).toBe(10);expect(s.value).toBe(60);expect(geometryDiagram(a)?.id).toBe('polygon-10')});
 it('solves a regular octagon area from side and apothem',()=>{const a=analyzeGeometryQuestion('A regular octagon has side 5 cm and apothem 6 cm. Find the area.');expect(solveGeometry(a).value).toBe(120);expect(geometryDiagram(a)?.primitives.length).toBeGreaterThan(1)});
 it('solves interior angle of a regular 12-gon',()=>{const a=analyzeGeometryQuestion('A regular 12-gon. Find each interior angle.');const s=solveGeometry(a);expect(s.value).toBe(150);expect(s.unit).toBe('°');expect(geometryDiagram(a)?.id).toBe('polygon-12')});
 it('solves exterior angle of an icosagon',()=>{const a=analyzeGeometryQuestion('A regular icosagon. Find each exterior angle.');expect(solveGeometry(a).value).toBe(18)});
});
describe('coordinate geometry engine',()=>{it('maps axis endpoints correctly',()=>{const a=coordinateAxes(-10,10,2);const ticks=a.filter(x=>x.semantic==='x-tick');expect(ticks[0].attrs.x1).toBe(10);expect(ticks[ticks.length-1].attrs.x1).toBe(90)});it('computes distance midpoint slope and transforms',()=>{expect(distance([0,0],[3,4])).toBe(5);expect(midpoint([0,2],[4,6])).toEqual([2,4]);expect(slope([1,1],[3,5])).toBe(2);const p=transformPoint([2,1],{rotateDeg:90,translateX:3});expect(p[0]).toBeCloseTo(2,6);expect(p[1]).toBeCloseTo(2,6)})});
describe('triangle construction geometry',()=>{it('computes classic centers and circles',()=>{const m=buildGeometry('triangle')!;const p=triangleConstructions(m,['centroid','incenter','circumcenter','orthocenter','incircle','circumcircle','altitude']);for(const s of['centroid','incenter','circumcenter','orthocenter','incircle','circumcircle','altitude'])expect(p.some(x=>x.semantic===s)).toBe(true)});});
describe('advanced geometry generators',()=>{it('renders parametric curves and quadrics',()=>{for(const id of['cardioid','lemniscate','astroid','cycloid','archimedean-spiral'])expect(buildParametricCurve(id)?.primitives.length).toBeGreaterThan(0);for(const id of['ellipsoid','elliptic-paraboloid','hyperbolic-paraboloid','one-sheet-hyperboloid'])expect(buildQuadric(id)?.primitives.length).toBeGreaterThan(3);expect(buildTorus().primitives.length).toBeGreaterThan(0)});it('renders fractals and regular tilings',()=>{expect(sierpinskiTriangle(3).primitives.length).toBe(27);expect(kochSnowflake(2).primitives.length).toBe(1);expect(cantorSet(3).primitives.length).toBe(15);for(const k of['triangular','square','hexagonal'] as const)expect(regularTiling(k,2,2).primitives.length).toBeGreaterThan(0)});it('renders space curves and knots',()=>{for(const id of['helix','elliptical-helix','conical-helix','trefoil-knot','figure-eight-knot','torus-knot'])expect(buildSpaceCurve(id)?.primitives.length).toBe(1)})});
describe('higher dimensional projections',()=>{it('projects a tesseract with 16 vertices and 32 edges',()=>{const m=tesseract();expect(m.id).toBe('4-cube');expect(m.primitives.length).toBe(32)});it('generates n-dimensional families',()=>{expect(hypercube(5).primitives.length).toBe(80);expect(simplex(4).primitives.length).toBe(10);expect(crossPolytope(4).primitives.length).toBe(24)})});
describe('special curves and topology surfaces',()=>{it('renders named advanced plane curves',()=>{for(const id of['cassini-oval','deltoid','nephroid','epicycloid','hypocycloid','euler-spiral','reuleaux-triangle'])expect(buildSpecialCurve(id)?.primitives.length).toBeGreaterThan(0)});it('renders university topology and minimal-surface examples',()=>{for(const id of['mobius-strip','helicoid','enneper-surface','klein-bottle'])expect(buildTopologySurface(id)?.primitives.length).toBeGreaterThan(100)})});
describe('spatial nets and cross sections',()=>{it('generates standard solid nets',()=>{for(const id of['cube','rectangular-prism','cylinder','cone'])expect(solidNet(id).length).toBeGreaterThan(1)});it('generates common cross sections',()=>{for(const id of['cylinder','cone','sphere','cube','rectangular-prism','pyramid'])expect(crossSection(id,'horizontal').length).toBeGreaterThan(0)})});
describe('complete Platonic mesh family',()=>{it('renders all five Platonic solids',()=>{const expected:Record<string,number>={tetrahedron:6,cube:12,octahedron:12,dodecahedron:30,icosahedron:30};for(const[id,edges]of Object.entries(expected)){const m=buildPolyhedron(id);expect(m).toBeTruthy();expect(m!.primitives.length).toBe(edges)}});});
describe('verification parity with supported solver',()=>{for(const[q]of cases)it('independently verifies '+q,()=>{const a=analyzeGeometryQuestion(q),s=solveGeometry(a),v=verifyGeometry(a,s);expect(s.success).toBe(true);expect(v.valid).toBe(true);expect(v.checks).toContain('Answer passes independent equation substitution.')});it('verifies regular polygon angle path',()=>{const a=analyzeGeometryQuestion('A regular decagon. Find each exterior angle.');expect(verifyGeometry(a,solveGeometry(a)).valid).toBe(true)});it('refuses to call an unsupported solved path verified',()=>{const a=analyzeGeometryQuestion('A circle has radius 2 cm. Find the area.');const fake={...solveGeometry(a),value:99};expect(verifyGeometry(a,fake).valid).toBe(false)});});
describe('polygon semantic safety',()=>{it('does not assume an ordinary named polygon is regular',()=>{const a=analyzeGeometryQuestion('An irregular pentagon has side 6 cm. Find the perimeter.');expect(a.regularPolygon).toBe(false);expect(solveGeometry(a).success).toBe(false);expect(geometryDiagram(a)?.id).toBe('polygon-5')});it('keeps polygon interior angle sum valid without regularity',()=>{const a=analyzeGeometryQuestion('A pentagon. Find the sum of the interior angles.');expect(a.regularPolygon).toBe(false);expect(solveGeometry(a).value).toBe(540)});it('requires regularity for each interior angle',()=>{const a=analyzeGeometryQuestion('A pentagon. Find each interior angle.');expect(solveGeometry(a).success).toBe(false)});});
describe('expanded school geometry paths',()=>{const qs=[['A right triangle has hypotenuse 13 cm and leg a 5 cm. Find the missing leg.',12],['A triangle has three sides 3 cm, 4 cm, and 5 cm. Find the perimeter.',12],['A triangular prism has base 6 cm, height 4 cm, length 10 cm, and base perimeter 16 cm. Find the surface area.',184],['A pyramid has base area 36 cm and height 9 cm. Find the volume.',108],['A semicircle has diameter 10 cm. Find the area.',39.2699],['A cylinder has diameter 8 cm and height 10 cm. Find the volume.',502.6548]] as const;for(const[q,v]of qs)it(q,()=>{const a=analyzeGeometryQuestion(q),s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBeCloseTo(v,3);expect(verifyGeometry(a,s).valid).toBe(true);expect(geometryDiagram(a)).toBeTruthy()})});
describe('circle sectors arcs and shape diagonals',()=>{const qs=[['A circle has radius 10 cm and central angle 90. Find the arc length.',15.708],['A circle has radius 10 cm and central angle 90. Find the sector area.',78.5398],['A rectangle has length 3 cm and width 4 cm. Find the diagonal.',5],['A square has side 6 cm. Find the diagonal.',8.4853]] as const;for(const[q,v]of qs)it(q,()=>{const a=analyzeGeometryQuestion(q),s=solveGeometry(a);expect(s.success).toBe(true);expect(s.value).toBeCloseTo(v,3);expect(verifyGeometry(a,s).valid).toBe(true)})});
describe('advanced topology integrity',()=>{it('dodecahedron dual has twelve cyclic pentagonal faces and thirty unique edges',async()=>{const{POLYHEDRON_MESHES}=await import('../visual/polyhedronMesh');const d=POLYHEDRON_MESHES.dodecahedron;expect(d.faces).toHaveLength(12);expect(d.faces.every(f=>f.length===5)).toBe(true);const edges=new Set<string>();for(const f of d.faces)for(let i=0;i<f.length;i++){const a=f[i],b=f[(i+1)%f.length];edges.add(a<b?`${a}-${b}`:`${b}-${a}`)}expect(edges.size).toBe(30)});it('renders additional classical fractal families',async()=>{const{dragonCurve,hilbertCurve,sierpinskiCarpet}=await import('../visual/fractalTilingGenerators');expect(sierpinskiCarpet(2).primitives.length).toBe(64);expect(dragonCurve(8).primitives.length).toBe(1);expect(hilbertCurve(4).primitives.length).toBe(1)})});
describe('complete triangle construction families',()=>{it('draws all three angle and perpendicular bisectors',async()=>{const{buildGeometry}=await import('../visual/geometryEngine'),{triangleConstructions}=await import('../visual/geometryConstructions');const m=buildGeometry('triangle',{})!;expect(triangleConstructions(m,['angle-bisector']).filter(x=>x.semantic==='angle-bisector')).toHaveLength(3);expect(triangleConstructions(m,['perpendicular-bisector']).filter(x=>x.semantic==='perpendicular-bisector')).toHaveLength(3)});it('adds university topology surfaces',async()=>{const{buildTopologySurface}=await import('../visual/topologySurfaceGenerators');for(const id of ['scherk-surface','roman-surface','projective-plane'])expect(buildTopologySurface(id)!.primitives.length).toBeGreaterThan(100)})});
describe('parameterized spatial geometry',()=>{it('changes rectangular-prism net with dimensions',async()=>{const{solidNet}=await import('../visual/spatialGeometry');const a=JSON.stringify(solidNet('rectangular-prism',{width:14,height:16,depth:9})),b=JSON.stringify(solidNet('rectangular-prism',{width:26,height:25,depth:17}));expect(a).not.toBe(b);expect(solidNet('rectangular-prism',{width:14,height:16,depth:9})).toHaveLength(6)});it('uses cylinder radius and height in its net',async()=>{const{solidNet}=await import('../visual/spatialGeometry');const a=solidNet('cylinder',{radius:7,height:22}),b=solidNet('cylinder',{radius:13,height:40});expect(JSON.stringify(a)).not.toBe(JSON.stringify(b));expect(a).toHaveLength(3)})});