export type GeometryStatus='planned'|'family-supported'|'implemented'|'tested';
export interface GeometryCoverageItem{id:string;name:string;dimension:string;category:string;family?:string;generator?:string;status:GeometryStatus;aliases?:string[]}

/**
 * Master coverage registry. "family-supported" means a parametric generator is responsible
 * for the member; it is not considered complete until representative and boundary tests pass.
 */
export const GEOMETRY_COVERAGE:GeometryCoverageItem[]=[
 {id:'polygon.general',name:'n-gon / General polygon',dimension:'2D',category:'polygon',generator:'Polygon(n, vertices, options)',status:'family-supported'},
 ...[
 ['triangle',3],['quadrilateral',4],['pentagon',5],['hexagon',6],['heptagon',7],['octagon',8],['nonagon',9],['decagon',10],['undecagon',11],['dodecagon',12],['tridecagon',13],['tetradecagon',14],['pentadecagon',15],['hexadecagon',16],['heptadecagon',17],['octadecagon',18],['enneadecagon',19],['icosagon',20]
 ].map(([name,n])=>({id:`polygon.${name}`,name:String(name),dimension:'2D',category:'polygon',family:'polygon.general',generator:`Polygon(${n})`,status:'family-supported' as const})),
 ...['regular','irregular','convex','concave','simple','complex-self-intersecting','equiangular','equilateral'].map(v=>({id:`polygon.variant.${v}`,name:`${v} polygon`,dimension:'2D',category:'polygon-variant',family:'polygon.general',generator:'Polygon(n, vertices, options)',status:'planned' as const})),
 {id:'star.general',name:'{n/k} star polygon',dimension:'2D',category:'star',generator:'StarPolygon(n,k)',status:'planned'},
 ...['equilateral','isosceles','scalene','acute','right','obtuse','isosceles-right','30-60-90','45-45-90'].map(v=>({id:`triangle.${v}`,name:`${v} triangle`,dimension:'2D',category:'triangle',family:'polygon.general',generator:'Triangle(constraints)',status:'planned' as const})),
 ...['square','rectangle','parallelogram','rhombus','trapezoid','isosceles-trapezoid','right-trapezoid','kite','dart','irregular-quadrilateral','cyclic-quadrilateral','tangential-quadrilateral','bicentric-quadrilateral'].map(v=>({id:`quad.${v}`,name:v,dimension:'2D',category:'quadrilateral',generator:'Quadrilateral(constraints)',status:['square','rectangle','parallelogram','rhombus','trapezoid','kite'].includes(v)?'implemented' as const:'planned' as const})),
 ...['circle','disk','semicircle','quarter-circle','arc','minor-arc','major-arc','sector','circular-segment','annulus','concentric-circles','tangent-circles','intersecting-circles'].map(v=>({id:`circular.${v}`,name:v,dimension:'2D',category:'circular',generator:'CircularGeometry(type, params)',status:['circle','semicircle','sector','annulus'].includes(v)?'implemented' as const:'planned' as const})),
 ...['ellipse','parabola','hyperbola','rectangular-hyperbola','degenerate-conic','intersecting-lines-conic','parallel-lines-conic','point-conic'].map(v=>({id:`conic.${v}`,name:v,dimension:'2D',category:'conic',generator:'Conic(type, coefficients)',status:['ellipse','parabola','hyperbola'].includes(v)?'implemented' as const:'planned' as const})),
 ...['oval','ovoid','reuleaux-triangle','reuleaux-polygon','lune','vesica-piscis','crescent','cardioid','limacon','lemniscate','cassini-oval','astroid','deltoid','nephroid','cycloid','epicycloid','hypocycloid','involute','catenary','archimedean-spiral','logarithmic-spiral','fermat-spiral','hyperbolic-spiral','euler-spiral'].map(v=>({id:`curve.${v}`,name:v,dimension:'2D',category:'curve',generator:'ParametricCurve(type, params)',status:'planned' as const})),
 ...['point','line','line-segment','ray','angle','coordinate-plane','vector','polyline','parametric-curve','polar-curve','algebraic-curve','bezier-curve','b-spline','spline','nurbs-curve'].map(v=>({id:`analytic.${v}`,name:v,dimension:'2D',category:'analytic',generator:'AnalyticObject(type, params)',status:'planned' as const})),

 {id:'prism.general',name:'n-gonal prism',dimension:'3D',category:'prism',generator:'Prism(n, options)',status:'planned'},
 {id:'pyramid.general',name:'n-gonal pyramid',dimension:'3D',category:'pyramid',generator:'Pyramid(n, options)',status:'planned'},
 {id:'antiprism.general',name:'n-gonal antiprism',dimension:'3D',category:'polyhedron',generator:'Antiprism(n)',status:'planned'},
 {id:'bipyramid.general',name:'n-gonal bipyramid',dimension:'3D',category:'polyhedron',generator:'Bipyramid(n)',status:'planned'},
 ...['cube','rectangular-prism','triangular-prism','pyramid','tetrahedron','octahedron','cylinder','cone','sphere','hemisphere','frustum'].map(v=>({id:`solid.${v}`,name:v,dimension:'3D',category:'solid',generator:'ProjectedSolid(type, params)',status:'implemented' as const})),
 ...['sphere','ball','spherical-cap','spherical-segment','spherical-sector','spherical-wedge','spherical-shell','right-cylinder','oblique-cylinder','elliptic-cylinder','parabolic-cylinder','hyperbolic-cylinder','generalized-cylinder','hollow-cylinder','right-cone','oblique-cone','elliptic-cone','double-cone','truncated-cone','conical-frustum'].map(v=>({id:`curved3d.${v}`,name:v,dimension:'3D',category:'curved-solid',generator:'ImplicitOrParametricSurface(type, params)',status:'planned' as const})),
 ...['torus','ring-torus','horn-torus','spindle-torus','torus-segment','clifford-torus'].map(v=>({id:`torus.${v}`,name:v,dimension:'3D/4D',category:'toroidal',generator:'TorusFamily(type, params)',status:'planned' as const})),
 ...['tetrahedron','cube','octahedron','dodecahedron','icosahedron'].map(v=>({id:`platonic.${v}`,name:v,dimension:'3D',category:'platonic',generator:'PolyhedronMesh(id)',status:['tetrahedron','cube','octahedron'].includes(v)?'implemented' as const:'planned' as const})),
 ...['truncated-tetrahedron','cuboctahedron','truncated-cube','truncated-octahedron','rhombicuboctahedron','truncated-cuboctahedron','snub-cube','icosidodecahedron','truncated-dodecahedron','truncated-icosahedron','rhombicosidodecahedron','truncated-icosidodecahedron','snub-dodecahedron'].map(v=>({id:`archimedean.${v}`,name:v,dimension:'3D',category:'archimedean',generator:'PolyhedronMesh(id)',status:'planned' as const})),
 ...['triakis-tetrahedron','rhombic-dodecahedron','triakis-octahedron','tetrakis-hexahedron','deltoidal-icositetrahedron','disdyakis-dodecahedron','pentagonal-icositetrahedron','rhombic-triacontahedron','triakis-icosahedron','pentakis-dodecahedron','deltoidal-hexecontahedron','disdyakis-triacontahedron','pentagonal-hexecontahedron'].map(v=>({id:`catalan.${v}`,name:v,dimension:'3D',category:'catalan',generator:'PolyhedronMesh(id)',status:'planned' as const})),
 {id:'johnson.family',name:'Johnson solids J1-J92',dimension:'3D',category:'johnson',generator:'JohnsonSolid(J)',status:'planned'},

 ...['ellipsoid','spheroid','oblate-spheroid','prolate-spheroid','elliptic-paraboloid','hyperbolic-paraboloid','one-sheet-hyperboloid','two-sheet-hyperboloid','elliptic-cone','circular-cone','elliptic-cylinder','hyperbolic-cylinder','parabolic-cylinder'].map(v=>({id:`quadric.${v}`,name:v,dimension:'3D',category:'quadric-surface',generator:'Quadric(coefficients)',status:'planned' as const})),
 ...['plane','graph-surface','parametric-surface','ruled-surface','surface-of-revolution','developable-surface','minimal-surface','catenoid','helicoid','enneper-surface','scherk-surface','mobius-strip','klein-bottle','projective-plane','boys-surface','roman-surface'].map(v=>({id:`surface.${v}`,name:v,dimension:'3D',category:'surface',generator:'ParametricSurface(type, params)',status:'planned' as const})),
 ...['helix','elliptical-helix','conical-helix','space-curve','parametric-space-curve','bezier-space-curve','spline-space-curve','trefoil-knot','figure-eight-knot','torus-knot','general-knot'].map(v=>({id:`spacecurve.${v}`,name:v,dimension:'3D',category:'space-curve',generator:'SpaceCurve(type, params)',status:'planned' as const})),
 ...['sierpinski-triangle','sierpinski-carpet','koch-curve','koch-snowflake','dragon-curve','hilbert-curve','peano-curve','mandelbrot-set','julia-set','cantor-set','sierpinski-tetrahedron','menger-sponge','fractal-tree-3d','mandelbulb'].map(v=>({id:`fractal.${v}`,name:v,dimension:v.includes('3d')||v.includes('tetrahedron')||v.includes('sponge')||v==='mandelbulb'?'3D':'2D',category:'fractal',generator:'Fractal(type, depth, params)',status:'planned' as const})),
 ...['triangular-tiling','square-tiling','hexagonal-tiling','regular-tessellation','semiregular-tessellation','uniform-tiling','penrose-tiling','voronoi','delaunay','honeycomb','polyhedral-honeycomb'].map(v=>({id:`tiling.${v}`,name:v,dimension:'2D/3D',category:'tiling',generator:'Tiling(type, params)',status:'planned' as const})),

 ...['5-cell','tesseract','16-cell','24-cell','120-cell','600-cell'].map(v=>({id:`polytope4.${v}`,name:v,dimension:'4D',category:'regular-4-polytope',generator:'Polytope4D(id, projection)',status:'planned' as const})),
 ...['4-simplex','4-cube','4-orthoplex','4d-hyperrectangle','4d-hypersphere','4-ball','3-sphere','4d-hyperellipsoid','4d-hypercone','4d-hypercylinder','duoprism','duopyramid','4d-prism','4d-pyramid','4d-torus'].map(v=>({id:`higher.${v}`,name:v,dimension:'4D',category:'higher-dimensional',generator:'HigherDimensional(type, projection)',status:'planned' as const})),
 {id:'nd.simplex',name:'n-simplex',dimension:'nD',category:'infinite-family',generator:'NSimplex(n)',status:'planned'},
 {id:'nd.hypercube',name:'n-cube / hypercube',dimension:'nD',category:'infinite-family',generator:'Hypercube(n)',status:'planned'},
 {id:'nd.orthoplex',name:'n-orthoplex / cross-polytope',dimension:'nD',category:'infinite-family',generator:'CrossPolytope(n)',status:'planned'}
];

export const geometryCoverageSummary=()=>GEOMETRY_COVERAGE.reduce((a,x)=>{a[x.status]=(a[x.status]??0)+1;return a},{} as Record<GeometryStatus,number>);
